name: Build and Deploy to io Repo

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout telog repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd blog-front  # front-blog 디렉토리로 이동
        npm install  # 의존성 설치
        npm install -g gatsby-cli  # gatsby-cli 글로벌 설치

    - name: Build the project
      run: |
        cd blog-front  # front-blog 디렉토리로 이동
        gatsby build  # Gatsby 빌드

    - name: Checkout io repository
      uses: actions/checkout@v3
      with:
        repository: codemasterli/codemasterli.github.io  # io 레포지토리
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy build files to io repo
      run: |
        cd blog-front  # blog-front 디렉토리로 이동
        rm -rf ./public/*  # io 레포지토리의 기존 파일 삭제
        cp -r ./public/* ./  # public 디렉토리의 파일을 io 레포지토리로 복사

    - name: Commit and push to io repo
      run: |
        git config --global user.name "임채명"
        git config --global user.email "dlacoaud92@naver.com"
        git add .
        git commit -m "Deploy latest build"
        git push origin master  # io 레포지토리의 master 브랜치에 푸시